version: '3.8'
services:
    api:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 8080:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        networks:
          - mssql_mssql

networks:
  mssql_mssql:
    external: true